"""
3D FNO — Predicts T_next directly (normalised).
8-channel input, region-weighted loss, pushforward, gentle physics.
Master's Thesis: Simulating Heat Treatment using OpenFOAM and AI

Physics rationale: The dataset is generated by OpenFOAM which already
solves the full Navier-Stokes + heat equations. The physics loss here
acts only as a gentle regulariser (static λ=0.003) to improve rollout
stability — the data itself already contains the physics.

v4 FINAL upgrades (April 2026):
  - AdamW optimizer with weight_decay=1e-4
  - Gaussian noise injection σ=0.01 (~2.66K) on input temperature
  - Static physics λ=0.003 (stable rollout)
  - Pushforward ramp 0→1.0, warmup 10%
"""
from __future__ import annotations
import sys, time, argparse, json, math
from pathlib import Path
import numpy as np
import torch
import torch.nn.functional as F

sys.path.insert(0, str(Path(__file__).parent))

from configs.fno_config import CONFIG
from data.dataset import get_fno3d_dataloaders
from models.fno_model import HeatTreatmentFNO3D
from utils.metrics import compute_metrics, within_tolerance
from utils.checkpoint import CheckpointManager
from utils.logging import setup_logging


# ── Curriculum schedules ──────────────────────────────────────

def get_physics_lambda(epoch, n_epochs):
    """
    Physics lambda = 0.001 constant (balanced 100:1 ratio).
    Rationale: With L_cond /10 normalization, 0.001 gives balanced 
    physics:data gradient contribution (~1:1 effective ratio).
    Physics acts as REGULARISER — OpenFOAM data already has full physics.
    Override via --lam CLI flag.
    """
    return 0.001  # balanced 100:1 ratio (L_cond normalized)


def get_pushforward_weight(epoch, n_epochs):
    """Pushforward ramp: off for first 10%, then linear to 1.0 (v4 upgrade)."""
    warmup_end = int(n_epochs * 0.10)
    if epoch <= warmup_end:
        return 0.0
    return 1.0 * (epoch - warmup_end) / (n_epochs - warmup_end)


def get_warmup_lr(epoch, base_lr, warmup_epochs=5):
    """Linear LR warmup for first 5 epochs."""
    if epoch <= warmup_epochs:
        return base_lr * (0.1 + 0.9 * epoch / warmup_epochs)
    return base_lr


# ── Loss functions ────────────────────────────────────────────

def weighted_mse(pred, target, weight):
    """MSE weighted by region importance (steel=10x, air=3x, outer=0.1x)."""
    diff2 = (pred - target).pow(2)
    w = weight.unsqueeze(1)
    return (diff2 * w).sum() / (w.sum() * pred.shape[1] + 1e-8)


def physics_loss_3d(pred, x, T_mean, T_std, cfg=None, dt=10.0, grid_spacing=None):
    """
    Professional physics-informed loss for FNO heat treatment surrogate.

    Based on energy conservation:
        rho*Cp*dT/dt = kappa*Laplacian(T) + h*(T_set-T)/delta + eps*sigma*(T_set^4-T^4)/delta

    Five terms:
      1. L_cond:   Fourier conduction with per-voxel alpha = kappa/(rho*Cp)
      2. L_conv:   Newton convection + overshoot constraint
      3. L_rad:    Stefan-Boltzmann radiation (T^4)
      4. L_eng:    combined energy balance
      5. L_smooth: spectral smoothness (FNO-specific, kept from original)
    """
    from configs.fno_config import SIGMA_SB, EMISSIVITY_STEEL, H_CONV, CHAR_THICKNESS

    if cfg is not None:
        dt = cfg.dt
        # Real grid spacings from furnace bounds / grid resolution
        dx = (cfg.x_max - cfg.x_min) / cfg.grid_x
        dy = (cfg.y_max - cfg.y_min) / cfg.grid_y
        dz = (cfg.z_max - cfg.z_min) / cfg.grid_z
    elif grid_spacing is not None:
        dx, dy, dz = grid_spacing
    else:
        # Fallback defaults (shouldn't be used in production)
        dx = dy = dz = 0.007

    # ----- Extract channels -----
    T_pred_norm = pred.squeeze(1)                # (B, Gx, Gy, Gz)
    T_cur_norm = x[:, 0]
    Tset_norm  = x[:, 1]
    is_heater  = x[:, 4]
    kappa_s    = x[:, 5]                         # = kappa / 100
    Cp_s       = x[:, 6]                         # = Cp / 1000
    rho_s      = x[:, 7]                         # = rho / 10000
    non_heater = (1.0 - is_heater)

    # ----- Denormalize to Kelvin -----
    T_pred_K = T_pred_norm * T_std + T_mean
    T_cur_K  = T_cur_norm  * T_std + T_mean
    Tset_K   = Tset_norm   * T_std + T_mean

    # ----- Recover raw SI materials -----
    kappa = kappa_s * 100.0                      # W/(m*K)
    Cp    = Cp_s    * 1000.0                     # J/(kg*K)
    rho   = rho_s   * 10000.0                    # kg/m^3

    # ----- Derived -----
    alpha  = kappa / (rho * Cp + 1e-8)           # m^2/s
    rho_cp = rho * Cp + 1e-8                     # J/(m^3*K)
    delta  = CHAR_THICKNESS
    dT_dt  = (T_pred_K - T_cur_K) / dt           # K/s

    # ========================================================
    # 1. CONDUCTION — Fourier with proper grid spacing
    # dT/dt = alpha * (d2T/dx2 + d2T/dy2 + d2T/dz2)
    # ========================================================
    lap_x = (T_cur_K[:, 2:,   1:-1, 1:-1] -
             2 * T_cur_K[:, 1:-1, 1:-1, 1:-1] +
             T_cur_K[:, :-2,  1:-1, 1:-1]) / (dx ** 2)
    lap_y = (T_cur_K[:, 1:-1, 2:,   1:-1] -
             2 * T_cur_K[:, 1:-1, 1:-1, 1:-1] +
             T_cur_K[:, 1:-1, :-2,  1:-1]) / (dy ** 2)
    lap_z = (T_cur_K[:, 1:-1, 1:-1, 2:] -
             2 * T_cur_K[:, 1:-1, 1:-1, 1:-1] +
             T_cur_K[:, 1:-1, 1:-1, :-2]) / (dz ** 2)
    lap_T = lap_x + lap_y + lap_z                # (B, Gx-2, Gy-2, Gz-2)

    alpha_i      = alpha[:,      1:-1, 1:-1, 1:-1]
    dT_dt_i      = dT_dt[:,      1:-1, 1:-1, 1:-1]
    non_heater_i = non_heater[:, 1:-1, 1:-1, 1:-1]

    dT_dt_cond_i = alpha_i * lap_T
    cond_res_i = (dT_dt_i - dT_dt_cond_i) / 10.0
    L_cond = (cond_res_i * non_heater_i).pow(2).mean()

    # ========================================================
    # 2. CONVECTION — Newton's cooling + overshoot
    # ========================================================
    dT_dt_conv = H_CONV * (Tset_K - T_cur_K) / (rho_cp * delta)
    conv_res = (dT_dt - dT_dt_conv) / 100.0  # proper scale (dT_dt_conv ~300 K/s)
    L_conv_match = (conv_res * non_heater).pow(2).mean()

    overshoot = F.relu(T_pred_norm - Tset_norm) * non_heater
    L_overshoot = overshoot.pow(2).mean()

    L_conv = 0.5 * L_conv_match + 0.5 * L_overshoot

    # ========================================================
    # 3. RADIATION — Stefan-Boltzmann
    # ========================================================
    dT_dt_rad = EMISSIVITY_STEEL * SIGMA_SB * (Tset_K.pow(4) - T_cur_K.pow(4)) / (rho_cp * delta)
    rad_res = (dT_dt - dT_dt_rad) / 1000.0  # proper scale (dT_dt_rad ~1000 K/s)
    L_rad = (rad_res * non_heater).pow(2).mean()

    # ========================================================
    # 4. ENERGY BALANCE — combined
    # ========================================================
    dT_dt_cond_full = torch.zeros_like(dT_dt)
    dT_dt_cond_full[:, 1:-1, 1:-1, 1:-1] = dT_dt_cond_i
    dT_dt_total = dT_dt_cond_full + dT_dt_conv + dT_dt_rad
    L_eng = ((dT_dt - dT_dt_total) * non_heater).pow(2).mean() / (T_std ** 2 + 1e-8)

    # ========================================================
    # 5. SPECTRAL SMOOTHNESS (FNO-specific, kept from original)
    # ========================================================
    pred_fft = torch.fft.rfftn(T_pred_norm, dim=[-3, -2, -1])
    Nx, Ny, Nz_half = pred_fft.shape[-3], pred_fft.shape[-2], pred_fft.shape[-1]
    cx = max(Nx // 3, 1)
    cy = max(Ny // 3, 1)
    cz = max(Nz_half // 3, 1)
    L_smooth = pred_fft[:, cx:, cy:, cz:].abs().pow(2).mean()

    # ========================================================
    # Weighted combination
    # ========================================================
    return (0.3  * L_cond +
            0.25 * L_conv +
            0.2  * L_rad +
            0.1  * L_eng +
            0.15 * L_smooth)



# ── Evaluation ────────────────────────────────────────────────

@torch.no_grad()
def evaluate(model, loader, device, train_ds, lam=0.0, cfg=None):
    """One-step validation with region-weighted loss and steel-specific MAE."""
    model.eval()
    total_data, total_wdata, total_phys, n = 0.0, 0.0, 0.0, 0
    all_pred, all_true = [], []
    steel_pred, steel_true = [], []
    T_mean, T_std = train_ds.T_mean, train_ds.T_std

    for batch in loader:
        x, y, T_cur, T_next_gt, weight = [
            b.to(device) if isinstance(b, torch.Tensor) else b for b in batch]
        pred = model(x)

        loss = F.mse_loss(pred, y)
        wloss = weighted_mse(pred, y, weight)
        total_data += loss.item()
        total_wdata += wloss.item()
        if lam > 1e-6:
            lp = physics_loss_3d(pred, x, T_mean, T_std, cfg=cfg)
            total_phys += lp.item()
        n += 1

        # Denormalise: pred is normalised T_next
        T_pred_K = (pred.squeeze(1).cpu().numpy() * T_std + T_mean).ravel()
        T_true_K = T_next_gt.cpu().numpy().ravel()
        all_pred.append(T_pred_K)
        all_true.append(T_true_K)

        # Steel-only metrics (region_id channel ≈ 0.0 = steel)
        rid = x[:, 2].cpu().numpy()
        is_steel = (rid < 0.05)
        if is_steel.any():
            T_p = (pred.squeeze(1).cpu().numpy() * T_std + T_mean)
            T_t = T_next_gt.cpu().numpy()
            steel_pred.append(T_p[is_steel])
            steel_true.append(T_t[is_steel])

    all_pred = np.concatenate(all_pred)
    all_true = np.concatenate(all_true)
    m = compute_metrics(all_pred, all_true)

    if steel_pred:
        sp = np.concatenate(steel_pred)
        st = np.concatenate(steel_true)
        m["steel_mae"] = float(np.mean(np.abs(sp - st)))
    else:
        m["steel_mae"] = 0.0

    avg_data = total_data / max(n, 1)
    avg_wdata = total_wdata / max(n, 1)
    avg_phys = total_phys / max(n, 1)
    m["loss_data"] = avg_data
    m["loss_wdata"] = avg_wdata
    m["loss_phys"] = avg_phys
    m["loss"] = avg_wdata
    m["within_5K"] = within_tolerance(all_pred, all_true, 5.0)
    return m


# ── Main ──────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--batch", type=int, default=4)
    parser.add_argument("--device", default=None)
    parser.add_argument("--test", action="store_true")
    parser.add_argument("--lam", type=float, default=None)
    parser.add_argument("--checkpoint_dir", type=str, default=None, help="Override checkpoint output folder")
    args = parser.parse_args()

    cfg = CONFIG
    if args.epochs: cfg.n_epochs = args.epochs
    if args.batch: cfg.batch_size = args.batch
    LAM_OVERRIDE = args.lam  # noqa: used by inline capture below
    device = torch.device(
        args.device if args.device
        else ("cuda" if torch.cuda.is_available() else "cpu"))

    sep = "=" * 70
    print(f"\n{sep}")
    print(f"  3D FNO — Physics-Regularised Training (8 channels)")
    print(f"  Device: {device}  Batch: {cfg.batch_size}  Epochs: {cfg.n_epochs}")
    print(f"  Grid: {cfg.grid_x}x{cfg.grid_y}x{cfg.grid_z}  "
          f"Modes: {cfg.fno_modes}  Layers: {cfg.fno_layers}  Latent: {cfg.fno_latent}")
    print(f"  Target: T_next normalised")
    print(f"  Physics: static λ=0.003 (stable baseline)")
    print(f"  Pushforward: w2 ramp 0→1.0 (epoch 10%→100%)")
    print(f"  Loss: region-weighted (steel=10x, air=3x, outer=0.1x)")
    print(f"{sep}\n")

    train_loader, val_loader, train_ds, val_ds = get_fno3d_dataloaders(cfg)

    T_mean = train_ds.T_mean
    T_std = train_ds.T_std
    print(f"  Stats: T_mean={T_mean:.1f}K  T_std={T_std:.1f}K\n")

    # Sanity test mode
    if args.test:
        print("  === SANITY TEST ===")
        batch = next(iter(train_loader))
        x, y, T_cur, T_next_gt, weight = batch
        print(f"  x: {x.shape}, y: {y.shape}, weight: {weight.shape}")
        print(f"  x channels: 8 = [T, Tset, rid, time, heater, kappa, Cp, rho]")
        print(f"  y range: [{y.min():.3f}, {y.max():.3f}] (normalised T_next)")
        print(f"  T_next range: [{T_next_gt.min():.1f}, {T_next_gt.max():.1f}]K")
        model = HeatTreatmentFNO3D(cfg).to(device)
        out = model(x.to(device))
        loss = weighted_mse(out, y.to(device), weight.to(device))
        loss.backward()
        print(f"  Forward+backward OK: loss={loss.item():.4f}")
        print(f"  === ALL CHECKS PASSED ===")
        return

    model = HeatTreatmentFNO3D(cfg).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, patience=15, factor=0.5, min_lr=1e-6)
    ckpt_dir = args.checkpoint_dir if args.checkpoint_dir else cfg.checkpoint_dir
    print(f"  Checkpoints will be saved to: {ckpt_dir}")
    ckpt_mgr = CheckpointManager(ckpt_dir)

    print(f"  {'Ep':>4} | {'TrWLoss':>9} | {'TrData':>9} | {'TrPhys':>9} | "
          f"{'VaWLoss':>9} | {'VaData':>9} | "
          f"{'MAE':>6} | {'Steel':>6} | {'R2':>7} | "
          f"{'lam':>6} | {'w2':>4} | {'Time':>5}")
    print(f"  {'-'*115}")

    t0 = time.time()
    for epoch in range(1, cfg.n_epochs + 1):
        lam = LAM_OVERRIDE if LAM_OVERRIDE is not None else get_physics_lambda(epoch, cfg.n_epochs)
        w2 = get_pushforward_weight(epoch, cfg.n_epochs)
        ep_start = time.time()

        lr = get_warmup_lr(epoch, args.lr, warmup_epochs=max(5, cfg.n_epochs // 10))
        for pg in optimizer.param_groups:
            pg['lr'] = lr

        model.train()
        total_loss, total_data, total_phys, nb = 0.0, 0.0, 0.0, 0

        for batch in train_loader:
            x, y, T_cur, T_next_gt, weight = [
                b.to(device) if isinstance(b, torch.Tensor) else b for b in batch]
            optimizer.zero_grad()
            
            # v4 upgrade: Noise injection (data augmentation)
            if model.training:
                noise_std = 0.01  # 1% = ~2.66K in Kelvin
                x = x.clone()
                x[:, 0] = x[:, 0] + noise_std * torch.randn_like(x[:, 0])

            # Step 1: predict T_next from ground truth T_current
            pred1 = model(x)
            loss1 = weighted_mse(pred1, y, weight)

            # Step 2: pushforward — use predicted T_next as new input
            loss_data = loss1
            if w2 > 1e-6:
                x2 = x.clone()
                x2[:, 0] = pred1.squeeze(1).detach()  # update T channel
                x2[:, 3] = x[:, 3] + cfg.dt / cfg.t_total   # advance time
                pred2 = model(x2)
                loss2 = weighted_mse(pred2, y, weight)  # approximate target
                loss_data = loss1 + w2 * loss2

            # Physics regulariser (gentle, λ ≤ 0.003)
            if lam > 1e-6:
                L_phys = physics_loss_3d(pred1, x, T_mean, T_std, cfg=cfg)
                loss = (1 - lam) * loss_data + lam * L_phys
                total_phys += L_phys.item()
            else:
                loss = loss_data

            loss.backward()
            if cfg.grad_clip > 0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), cfg.grad_clip)
            optimizer.step()
            total_loss += loss.item()
            total_data += loss1.item()
            nb += 1

        tr_loss = total_loss / max(nb, 1)
        tr_data = total_data / max(nb, 1)
        tr_phys = total_phys / max(nb, 1)

        val_m = evaluate(model, val_loader, device, train_ds, lam=lam, cfg=cfg)
        if epoch > 5:
            scheduler.step(val_m["loss"])

        is_best = ckpt_mgr.update(model, optimizer, scheduler, epoch, val_m)
        if epoch % 10 == 0:
            ckpt_mgr.save_periodic(model, optimizer, scheduler, epoch, val_m)

        ep_time = time.time() - ep_start
        tag = " *" if is_best else ""
        print(f"  {epoch:>4} | {tr_loss:>9.5f} | {tr_data:>9.5f} | "
              f"{tr_phys:>9.5f} | {val_m['loss_wdata']:>9.5f} | "
              f"{val_m['loss_data']:>9.5f} | "
              f"{val_m['mae']:>6.2f} | {val_m['steel_mae']:>6.2f} | "
              f"{val_m['r2']:>7.4f} | "
              f"{lam:>6.4f} | {w2:>4.2f} | {ep_time:>5.0f}s{tag}")

    total_time = time.time() - t0
    print(f"\n  Training done in {total_time/60:.1f} min ({total_time/3600:.2f} hrs)")
    print(f"  Best MAE: {ckpt_mgr.best_mae:.3f}K (epoch {ckpt_mgr.best_epoch})")

    # ── Inference speed test (RQ2) ────────────────────────────
    print(f"\n  === INFERENCE SPEED TEST (RQ2: Digital Twin Speedup) ===")
    model.eval()
    batch = next(iter(val_loader))
    x_test = batch[0].to(device)
    with torch.no_grad():
        for _ in range(10):  # warmup
            _ = model(x_test)
    if device.type == "cuda":
        torch.cuda.synchronize()
    t_inf = time.time()
    with torch.no_grad():
        for _ in range(100):
            _ = model(x_test)
    if device.type == "cuda":
        torch.cuda.synchronize()
    t_inf = (time.time() - t_inf) / 100
    t_full = t_inf * int(cfg.t_total / cfg.dt)
    print(f"  Single step: {t_inf*1000:.2f} ms")
    print(f"  Full rollout (400 steps): {t_full:.2f}s")
    print(f"  Speedup vs OpenFOAM (~3h): ~{3600*3/t_full:.0f}x")

    # ── Post-training rollout evaluation ──────────────────────
    print(f"\n  === ROLLOUT EVALUATION ===")
    print(f"  Loading best model for autoregressive rollout...")
    best_model = HeatTreatmentFNO3D.load(ckpt_mgr.best_path, cfg, str(device))
    try:
        from evaluation.evaluate import run_fno3d_evaluation
        run_fno3d_evaluation(best_model, cfg, device=str(device))
    except Exception as e:
        print(f"  Rollout evaluation failed: {e}")
        print(f"  Run separately: python evaluation/evaluate.py --device {device}")


if __name__ == "__main__":
    main()
