"""
3D FNO training — predicts T_next directly (normalised, full field
not delta).

8-channel voxel input, region-weighted data loss, pushforward
regularisation, and a gentle physics-informed regulariser on top.

Why physics is a *regulariser* and not a hard constraint here:
  The dataset itself is generated by OpenFOAM, which already solves
  the full Navier-Stokes + heat equations on every cell. The data
  contains the physics — the FNO just has to learn the operator
  that maps it forward in time. So the physics term doesn't carry
  the run; it nudges the model toward energy-balance-consistent
  predictions during the long autoregressive rollout, which keeps
  Phase-2 errors from blowing up.
"""
from __future__ import annotations
import sys, time, argparse, json, math
from pathlib import Path
import numpy as np
import torch
import torch.nn.functional as F

# Make the project importable from this top-level training script
sys.path.insert(0, str(Path(__file__).parent))

from configs.fno_config import CONFIG
from data.dataset import get_fno3d_dataloaders
from models.fno_model import HeatTreatmentFNO3D
from utils.metrics import compute_metrics, within_tolerance
from utils.checkpoint import CheckpointManager
from utils.logging import setup_logging


# ---- training schedules ----------------------------------------------
# Three small functions, each controls one knob over the course of
# training: physics weight, pushforward weight, and the LR warmup.

def get_physics_lambda(epoch, n_epochs):
    """
    Constant physics weight at 0.001.

    With L_cond divided by /10 inside the physics loss, this gives
    roughly a balanced 1:1 effective gradient ratio between the
    physics and data branches. The physics term is acting as a
    soft regulariser here — the OpenFOAM data already encodes the
    full physics, so nothing more aggressive is needed. Override
    via the --lam CLI flag if a sweep wants something different.
    """
    return 0.001


def get_pushforward_weight(epoch, n_epochs):
    """
    Pushforward (predict-then-feed-back) ramp.

    Held off for the first 10% of training so the model can lock
    onto a stable single-step mapping before being asked to absorb
    its own errors. After that the weight ramps linearly from 0 to
    1 over the remaining epochs.
    """
    warmup_end = int(n_epochs * 0.10)
    if epoch <= warmup_end:
        return 0.0
    return 1.0 * (epoch - warmup_end) / (n_epochs - warmup_end)


def get_warmup_lr(epoch, base_lr, warmup_epochs=5):
    """
    Linear LR warmup. Starts at 10% of the target LR on epoch 1 and
    ramps up to the full LR by `warmup_epochs`. After that
    ReduceLROnPlateau takes over.
    """
    if epoch <= warmup_epochs:
        return base_lr * (0.1 + 0.9 * epoch / warmup_epochs)
    return base_lr


# ---- loss functions --------------------------------------------------

def weighted_mse(pred, target, weight):
    """
    Region-weighted MSE.

    weight is the per-voxel region weight grid built by the dataset:
    steel=10x, air=3x, others=0.1x. Same scheme as the GNN, so the
    two architectures are graded on equal terms.
    """
    diff2 = (pred - target).pow(2)
    w = weight.unsqueeze(1)
    return (diff2 * w).sum() / (w.sum() * pred.shape[1] + 1e-8)


def physics_loss_3d(pred, x, T_mean, T_std, cfg=None, dt=10.0, grid_spacing=None):
    """
    Physics-informed loss for the FNO heat-treatment surrogate.

    Built on the energy balance:
        rho*Cp*dT/dt = kappa*Laplacian(T)
                     + h*(T_set - T) / delta
                     + eps*sigma*(T_set^4 - T^4) / delta

    Five residual terms:
      1. L_cond:   Fourier conduction (per-voxel alpha = kappa/(rho*Cp))
      2. L_conv:   Newton convection + an overshoot guard
      3. L_rad:    Stefan-Boltzmann radiation (T^4 dominant at 1100 C)
      4. L_eng:    combined energy-balance residual
      5. L_smooth: spectral smoothness penalty — FNO-specific, kept
                   from earlier experiments because it reliably damped
                   the high-frequency artefacts that show up on the
                   voxel grid otherwise

    Each residual is divided by its own characteristic scale so all
    five land in roughly the same numerical range — otherwise the
    radiation term (~1000 K/s at 1100 C) would swamp everything else.
    """
    from configs.fno_config import SIGMA_SB, EMISSIVITY_STEEL, H_CONV, CHAR_THICKNESS

    # ---- grid spacing (Δx, Δy, Δz) for the Laplacian ---------------
    # Read from the config when available, since they're derived from
    # the actual furnace bounds and grid resolution. The fallback is
    # only there to keep the function callable in unit tests.
    if cfg is not None:
        dt = cfg.dt
        dx = (cfg.x_max - cfg.x_min) / cfg.grid_x
        dy = (cfg.y_max - cfg.y_min) / cfg.grid_y
        dz = (cfg.z_max - cfg.z_min) / cfg.grid_z
    elif grid_spacing is not None:
        dx, dy, dz = grid_spacing
    else:
        dx = dy = dz = 0.007

    # ---- pull the relevant channels off the input tensor -----------
    T_pred_norm = pred.squeeze(1)                # (B, Gx, Gy, Gz)
    T_cur_norm = x[:, 0]
    Tset_norm  = x[:, 1]
    is_heater  = x[:, 4]
    kappa_s    = x[:, 5]                         # = kappa / 100
    Cp_s       = x[:, 6]                         # = Cp / 1000
    rho_s      = x[:, 7]                         # = rho / 10000
    non_heater = (1.0 - is_heater)

    # Bring temperatures back into Kelvin so the residuals can be
    # written in plain SI units.
    T_pred_K = T_pred_norm * T_std + T_mean
    T_cur_K  = T_cur_norm  * T_std + T_mean
    Tset_K   = Tset_norm   * T_std + T_mean

    # Recover raw SI material values from the normalised channels —
    # has to undo the same /100, /1000, /10000 scaling that the
    # dataset applied at sample time.
    kappa = kappa_s * 100.0                      # W/(m*K)
    Cp    = Cp_s    * 1000.0                     # J/(kg*K)
    rho   = rho_s   * 10000.0                    # kg/m^3

    # Derived physical quantities
    alpha  = kappa / (rho * Cp + 1e-8)           # thermal diffusivity, m^2/s
    rho_cp = rho * Cp + 1e-8                     # volumetric heat capacity
    delta  = CHAR_THICKNESS                      # V/A characteristic length
    dT_dt  = (T_pred_K - T_cur_K) / dt           # K/s

    # ---- 1. Conduction — Fourier with proper grid spacing ----------
    # 7-point stencil Laplacian on the voxel grid. Boundary voxels
    # are skipped (the [1:-1, 1:-1, 1:-1] slicing) to avoid the
    # one-sided differences that would otherwise need special-casing.
    lap_x = (T_cur_K[:, 2:,   1:-1, 1:-1] -
             2 * T_cur_K[:, 1:-1, 1:-1, 1:-1] +
             T_cur_K[:, :-2,  1:-1, 1:-1]) / (dx ** 2)
    lap_y = (T_cur_K[:, 1:-1, 2:,   1:-1] -
             2 * T_cur_K[:, 1:-1, 1:-1, 1:-1] +
             T_cur_K[:, 1:-1, :-2,  1:-1]) / (dy ** 2)
    lap_z = (T_cur_K[:, 1:-1, 1:-1, 2:] -
             2 * T_cur_K[:, 1:-1, 1:-1, 1:-1] +
             T_cur_K[:, 1:-1, 1:-1, :-2]) / (dz ** 2)
    lap_T = lap_x + lap_y + lap_z                # (B, Gx-2, Gy-2, Gz-2)

    # Slice the rate and material arrays to match the Laplacian shape
    alpha_i      = alpha[:,      1:-1, 1:-1, 1:-1]
    dT_dt_i      = dT_dt[:,      1:-1, 1:-1, 1:-1]
    non_heater_i = non_heater[:, 1:-1, 1:-1, 1:-1]

    dT_dt_cond_i = alpha_i * lap_T
    cond_res_i = (dT_dt_i - dT_dt_cond_i) / 10.0   # /10 to keep it ~O(1)
    L_cond = (cond_res_i * non_heater_i).pow(2).mean()

    # ---- 2. Convection — Newton's cooling + overshoot guard --------
    # Plus a soft penalty against predicting T_next > T_set, since
    # that's physically impossible during heating.
    dT_dt_conv = H_CONV * (Tset_K - T_cur_K) / (rho_cp * delta)
    conv_res = (dT_dt - dT_dt_conv) / 100.0        # dT_dt_conv tops out ~300 K/s
    L_conv_match = (conv_res * non_heater).pow(2).mean()

    overshoot = F.relu(T_pred_norm - Tset_norm) * non_heater
    L_overshoot = overshoot.pow(2).mean()

    L_conv = 0.5 * L_conv_match + 0.5 * L_overshoot

    # ---- 3. Radiation — Stefan-Boltzmann ---------------------------
    # T^4 dependence dominates the heating physics at 900-1100 C.
    dT_dt_rad = EMISSIVITY_STEEL * SIGMA_SB * (Tset_K.pow(4) - T_cur_K.pow(4)) / (rho_cp * delta)
    rad_res = (dT_dt - dT_dt_rad) / 1000.0          # dT_dt_rad ~1000 K/s
    L_rad = (rad_res * non_heater).pow(2).mean()

    # ---- 4. Energy balance — combined residual ---------------------
    # Pad the conduction term back out to the full grid so all three
    # rate fields can be summed cleanly. Boundary voxels contribute
    # zero conduction, which is fine for a soft regulariser.
    dT_dt_cond_full = torch.zeros_like(dT_dt)
    dT_dt_cond_full[:, 1:-1, 1:-1, 1:-1] = dT_dt_cond_i
    dT_dt_total = dT_dt_cond_full + dT_dt_conv + dT_dt_rad
    L_eng = ((dT_dt - dT_dt_total) * non_heater).pow(2).mean() / (T_std ** 2 + 1e-8)

    # ---- 5. Spectral smoothness — FNO-specific ---------------------
    # Penalise energy in the upper two-thirds of the spectrum. The
    # FNO can otherwise spit out high-frequency speckle on the voxel
    # grid that survives even though the L2 loss is small. This term
    # is what stopped that pattern in earlier sweeps.
    pred_fft = torch.fft.rfftn(T_pred_norm, dim=[-3, -2, -1])
    Nx, Ny, Nz_half = pred_fft.shape[-3], pred_fft.shape[-2], pred_fft.shape[-1]
    cx = max(Nx // 3, 1)
    cy = max(Ny // 3, 1)
    cz = max(Nz_half // 3, 1)
    L_smooth = pred_fft[:, cx:, cy:, cz:].abs().pow(2).mean()

    # ---- weighted combination --------------------------------------
    # Conduction and convection get the bulk of the weight since
    # they dominate inside the workpiece; radiation gets less because
    # it's already huge in raw magnitude; the energy-balance term is
    # a soft global constraint; the smoothness term is the FNO patch.
    return (0.3  * L_cond +
            0.25 * L_conv +
            0.2  * L_rad +
            0.1  * L_eng +
            0.15 * L_smooth)


# ---- evaluation -----------------------------------------------------

@torch.no_grad()
def evaluate(model, loader, device, train_ds, lam=0.0, cfg=None):
    """
    One-step validation pass.

    Reports the region-weighted loss, the unweighted data MSE, and
    overall + steel-only MAE in physical units. The steel MAE is the
    headline number that ends up in Table 5.2 of the thesis.
    """
    model.eval()
    total_data, total_wdata, total_phys, n = 0.0, 0.0, 0.0, 0
    all_pred, all_true = [], []
    steel_pred, steel_true = [], []
    T_mean, T_std = train_ds.T_mean, train_ds.T_std

    for batch in loader:
        x, y, T_cur, T_next_gt, weight = [
            b.to(device) if isinstance(b, torch.Tensor) else b for b in batch]
        pred = model(x)

        loss = F.mse_loss(pred, y)
        wloss = weighted_mse(pred, y, weight)
        total_data += loss.item()
        total_wdata += wloss.item()
        if lam > 1e-6:
            lp = physics_loss_3d(pred, x, T_mean, T_std, cfg=cfg)
            total_phys += lp.item()
        n += 1

        # Denormalise back to Kelvin for the physical-unit metrics
        T_pred_K = (pred.squeeze(1).cpu().numpy() * T_std + T_mean).ravel()
        T_true_K = T_next_gt.cpu().numpy().ravel()
        all_pred.append(T_pred_K)
        all_true.append(T_true_K)

        # Steel-only metrics — region IDs are stored as float i/11,
        # so steel (rid 0) shows up as 0.0/11 = 0.0 in the channel.
        rid = x[:, 2].cpu().numpy()
        is_steel = (rid < 0.05)
        if is_steel.any():
            T_p = (pred.squeeze(1).cpu().numpy() * T_std + T_mean)
            T_t = T_next_gt.cpu().numpy()
            steel_pred.append(T_p[is_steel])
            steel_true.append(T_t[is_steel])

    all_pred = np.concatenate(all_pred)
    all_true = np.concatenate(all_true)
    m = compute_metrics(all_pred, all_true)

    if steel_pred:
        sp = np.concatenate(steel_pred)
        st = np.concatenate(steel_true)
        m["steel_mae"] = float(np.mean(np.abs(sp - st)))
    else:
        m["steel_mae"] = 0.0

    avg_data = total_data / max(n, 1)
    avg_wdata = total_wdata / max(n, 1)
    avg_phys = total_phys / max(n, 1)
    m["loss_data"] = avg_data
    m["loss_wdata"] = avg_wdata
    m["loss_phys"] = avg_phys
    # Model selection runs on the weighted data loss — same signal
    # the optimiser is following, just evaluated on the val set.
    m["loss"] = avg_wdata
    m["within_5K"] = within_tolerance(all_pred, all_true, 5.0)
    return m


# ---- main -----------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--batch", type=int, default=4)
    parser.add_argument("--device", default=None)
    parser.add_argument("--test", action="store_true",
                        help="Run a quick 1-batch sanity test and exit")
    parser.add_argument("--lam", type=float, default=None,
                        help="Override the physics lambda set by the schedule")
    parser.add_argument("--checkpoint_dir", type=str, default=None,
                        help="Override the default checkpoint output folder")
    args = parser.parse_args()

    cfg = CONFIG
    if args.epochs: cfg.n_epochs = args.epochs
    if args.batch: cfg.batch_size = args.batch
    LAM_OVERRIDE = args.lam
    device = torch.device(
        args.device if args.device
        else ("cuda" if torch.cuda.is_available() else "cpu"))

    sep = "=" * 70
    print(f"\n{sep}")
    print(f"  3D FNO — Physics-Regularised Training (8 channels)")
    print(f"  Device: {device}  Batch: {cfg.batch_size}  Epochs: {cfg.n_epochs}")
    print(f"  Grid: {cfg.grid_x}x{cfg.grid_y}x{cfg.grid_z}  "
          f"Modes: {cfg.fno_modes}  Layers: {cfg.fno_layers}  Latent: {cfg.fno_latent}")
    print(f"  Target: T_next normalised")
    print(f"  Physics: static λ=0.001 (gentle regulariser)")
    print(f"  Pushforward: w2 ramp 0→1.0 (epoch 10%→100%)")
    print(f"  Loss: region-weighted (steel=10x, air=3x, outer=0.1x)")
    print(f"{sep}\n")

    train_loader, val_loader, train_ds, val_ds = get_fno3d_dataloaders(cfg)

    T_mean = train_ds.T_mean
    T_std = train_ds.T_std
    print(f"  Stats: T_mean={T_mean:.1f}K  T_std={T_std:.1f}K\n")

    # ---- sanity test mode ------------------------------------------
    # Quick smoke test: load one batch, run forward + backward,
    # check the shapes and a few sanity numbers. Useful for catching
    # dataset/model wiring problems without waiting for a real epoch.
    if args.test:
        print("  === SANITY TEST ===")
        batch = next(iter(train_loader))
        x, y, T_cur, T_next_gt, weight = batch
        print(f"  x: {x.shape}, y: {y.shape}, weight: {weight.shape}")
        print(f"  x channels: 8 = [T, Tset, rid, time, heater, kappa, Cp, rho]")
        print(f"  y range: [{y.min():.3f}, {y.max():.3f}] (normalised T_next)")
        print(f"  T_next range: [{T_next_gt.min():.1f}, {T_next_gt.max():.1f}]K")
        model = HeatTreatmentFNO3D(cfg).to(device)
        out = model(x.to(device))
        loss = weighted_mse(out, y.to(device), weight.to(device))
        loss.backward()
        print(f"  Forward+backward OK: loss={loss.item():.4f}")
        print(f"  === ALL CHECKS PASSED ===")
        return

    # ---- full training run -----------------------------------------
    model = HeatTreatmentFNO3D(cfg).to(device)
    # AdamW + small weight decay — same setup that worked for the GNN
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    # Plateau scheduler for the post-warmup phase. min_lr stops the
    # decay before things get silly close to zero.
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, patience=15, factor=0.5, min_lr=1e-6)

    # Default checkpoint dir lives under cfg.checkpoint_dir;
    # --checkpoint_dir lets the SLURM script point each run at its
    # own folder so concurrent runs don't clobber each other.
    ckpt_dir = args.checkpoint_dir if args.checkpoint_dir else cfg.checkpoint_dir
    print(f"  Checkpoints will be saved to: {ckpt_dir}")
    ckpt_mgr = CheckpointManager(ckpt_dir)

    # ---- log table header ------------------------------------------
    print(f"  {'Ep':>4} | {'TrWLoss':>9} | {'TrData':>9} | {'TrPhys':>9} | "
          f"{'VaWLoss':>9} | {'VaData':>9} | "
          f"{'MAE':>6} | {'Steel':>6} | {'R2':>7} | "
          f"{'lam':>6} | {'w2':>4} | {'Time':>5}")
    print(f"  {'-'*115}")

    t0 = time.time()
    for epoch in range(1, cfg.n_epochs + 1):
        # Schedule knobs for this epoch (lambda, pushforward, LR)
        lam = LAM_OVERRIDE if LAM_OVERRIDE is not None else get_physics_lambda(epoch, cfg.n_epochs)
        w2 = get_pushforward_weight(epoch, cfg.n_epochs)
        ep_start = time.time()

        lr = get_warmup_lr(epoch, args.lr, warmup_epochs=max(5, cfg.n_epochs // 10))
        for pg in optimizer.param_groups:
            pg['lr'] = lr

        model.train()
        total_loss, total_data, total_phys, nb = 0.0, 0.0, 0.0, 0

        for batch in train_loader:
            x, y, T_cur, T_next_gt, weight = [
                b.to(device) if isinstance(b, torch.Tensor) else b for b in batch]
            optimizer.zero_grad()

            # Light Gaussian noise on the temperature channel during
            # training — the standard MeshGraphNet trick for stabilising
            # autoregressive rollouts. ~2.66 K in physical units after
            # de-standardising.
            if model.training:
                noise_std = 0.01
                x = x.clone()
                x[:, 0] = x[:, 0] + noise_std * torch.randn_like(x[:, 0])

            # Step 1: predict T_next from the ground-truth T_current
            pred1 = model(x)
            loss1 = weighted_mse(pred1, y, weight)

            # Step 2: pushforward — feed the model's own prediction
            # back in as the next T_current. This is what teaches
            # the FNO to absorb its own errors during the long
            # autoregressive rollout at evaluation time.
            loss_data = loss1
            if w2 > 1e-6:
                x2 = x.clone()
                x2[:, 0] = pred1.squeeze(1).detach()      # update T channel
                x2[:, 3] = x[:, 3] + cfg.dt / cfg.t_total # advance time channel
                pred2 = model(x2)
                # Approximate the t+2 target with the t+1 target —
                # the dataset doesn't expose t+2 cleanly, but this
                # is enough to penalise drift across consecutive steps.
                loss2 = weighted_mse(pred2, y, weight)
                loss_data = loss1 + w2 * loss2

            # Physics regulariser — gentle weight, just nudges the
            # solution toward energy-balance consistency
            if lam > 1e-6:
                L_phys = physics_loss_3d(pred1, x, T_mean, T_std, cfg=cfg)
                loss = (1 - lam) * loss_data + lam * L_phys
                total_phys += L_phys.item()
            else:
                loss = loss_data

            loss.backward()
            if cfg.grad_clip > 0:
                # Hard clip on the gradient norm — kept around because
                # early epochs occasionally produced spikes that would
                # otherwise destabilise the InstanceNorms in the FNO
                # spectral blocks.
                torch.nn.utils.clip_grad_norm_(model.parameters(), cfg.grad_clip)
            optimizer.step()
            total_loss += loss.item()
            total_data += loss1.item()
            nb += 1

        tr_loss = total_loss / max(nb, 1)
        tr_data = total_data / max(nb, 1)
        tr_phys = total_phys / max(nb, 1)

        val_m = evaluate(model, val_loader, device, train_ds, lam=lam, cfg=cfg)
        # Hold the plateau scheduler off for the first 5 epochs so
        # the LR warmup gets to do its job uninterrupted.
        if epoch > 5:
            scheduler.step(val_m["loss"])

        is_best = ckpt_mgr.update(model, optimizer, scheduler, epoch, val_m)
        if epoch % 10 == 0:
            ckpt_mgr.save_periodic(model, optimizer, scheduler, epoch, val_m)

        ep_time = time.time() - ep_start
        tag = " *" if is_best else ""
        print(f"  {epoch:>4} | {tr_loss:>9.5f} | {tr_data:>9.5f} | "
              f"{tr_phys:>9.5f} | {val_m['loss_wdata']:>9.5f} | "
              f"{val_m['loss_data']:>9.5f} | "
              f"{val_m['mae']:>6.2f} | {val_m['steel_mae']:>6.2f} | "
              f"{val_m['r2']:>7.4f} | "
              f"{lam:>6.4f} | {w2:>4.2f} | {ep_time:>5.0f}s{tag}")

    total_time = time.time() - t0
    print(f"\n  Training done in {total_time/60:.1f} min ({total_time/3600:.2f} hrs)")
    print(f"  Best MAE: {ckpt_mgr.best_mae:.3f}K (epoch {ckpt_mgr.best_epoch})")

    # ---- inference speed test (RQ2) --------------------------------
    # Quick benchmark of the trained FNO so the speed-up numbers in
    # the thesis can be reproduced from any run. 10-pass warmup,
    # then average over 100 timed forward passes.
    print(f"\n  === INFERENCE SPEED TEST (RQ2: Digital Twin Speedup) ===")
    model.eval()
    batch = next(iter(val_loader))
    x_test = batch[0].to(device)
    with torch.no_grad():
        for _ in range(10):  # warmup
            _ = model(x_test)
    if device.type == "cuda":
        torch.cuda.synchronize()
    t_inf = time.time()
    with torch.no_grad():
        for _ in range(100):
            _ = model(x_test)
    if device.type == "cuda":
        torch.cuda.synchronize()
    t_inf = (time.time() - t_inf) / 100
    t_full = t_inf * int(cfg.t_total / cfg.dt)
    print(f"  Single step: {t_inf*1000:.2f} ms")
    print(f"  Full rollout (400 steps): {t_full:.2f}s")
    print(f"  Speedup vs OpenFOAM (~3h): ~{3600*3/t_full:.0f}x")

    # ---- post-training rollout evaluation --------------------------
    # Reload the best checkpoint and run the full autoregressive
    # rollout evaluation. Wrapped in try/except so a transient
    # rollout error doesn't trash the whole training run — those
    # numbers can always be regenerated from evaluation/evaluate.py.
    print(f"\n  === ROLLOUT EVALUATION ===")
    print(f"  Loading best model for autoregressive rollout...")
    best_model = HeatTreatmentFNO3D.load(ckpt_mgr.best_path, cfg, str(device))
    try:
        from evaluation.evaluate import run_fno3d_evaluation
        run_fno3d_evaluation(best_model, cfg, device=str(device))
    except Exception as e:
        print(f"  Rollout evaluation failed: {e}")
        print(f"  Run separately: python evaluation/evaluate.py --device {device}")


if __name__ == "__main__":
    main()